# Generated by Django 5.2.9 on 2025-12-28 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("UdyanSaathiAPI", "0004_mapdatamodel_stationscoordinatesmodel_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FleetAsset",
            fields=[
                (
                    "asset_id",
                    models.CharField(
                        max_length=20, primary_key=True, serialize=False, unique=True
                    ),
                ),
                (
                    "asset_type",
                    models.CharField(
                        choices=[
                            ("SMOG_GUN", "Smog Gun"),
                            ("SPRINKLER", "Water Sprinkler"),
                            ("DRONE", "Monitoring Drone"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("IDLE", "Idle"),
                            ("DISPATCHED", "Dispatched"),
                            ("ACTIVE", "Active"),
                            ("RETURNING", "Returning"),
                            ("MAINTENANCE", "Maintenance"),
                        ],
                        default="IDLE",
                        max_length=20,
                    ),
                ),
                ("current_lat", models.FloatField()),
                ("current_lon", models.FloatField()),
                ("home_station", models.CharField(max_length=100)),
                ("water_level_pct", models.IntegerField(default=100)),
                ("fuel_level_pct", models.IntegerField(default=100)),
                ("operational_hours", models.FloatField(default=0.0)),
                ("last_maintenance", models.DateTimeField(auto_now_add=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "fleet_assets",
            },
        ),
        migrations.CreateModel(
            name="DispatchTicket",
            fields=[
                (
                    "ticket_id",
                    models.CharField(
                        max_length=30, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("target_station", models.CharField(max_length=100)),
                ("target_lat", models.FloatField()),
                ("target_lon", models.FloatField()),
                ("predicted_pm25", models.FloatField()),
                ("predicted_aqi", models.IntegerField()),
                ("forecast_time", models.DateTimeField()),
                (
                    "urgency_level",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("MEDIUM", "Medium"),
                            ("HIGH", "High"),
                            ("CRITICAL", "Critical"),
                        ],
                        max_length=20,
                    ),
                ),
                ("mission_brief", models.TextField()),
                ("dispatch_time", models.DateTimeField(auto_now_add=True)),
                ("estimated_arrival", models.DateTimeField()),
                ("actual_arrival", models.DateTimeField(blank=True, null=True)),
                ("is_completed", models.BooleanField(default=False)),
                ("completion_time", models.DateTimeField(blank=True, null=True)),
                ("effectiveness_score", models.FloatField(blank=True, null=True)),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="missions",
                        to="UdyanSaathiAPI.fleetasset",
                    ),
                ),
            ],
            options={
                "db_table": "dispatch_tickets",
                "ordering": ["-dispatch_time"],
            },
        ),
        migrations.CreateModel(
            name="InterventionLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pre_intervention_pm25", models.FloatField()),
                ("pre_intervention_aqi", models.IntegerField()),
                ("post_intervention_pm25", models.FloatField()),
                ("post_intervention_aqi", models.IntegerField()),
                ("reduction_percentage", models.FloatField()),
                ("intervention_duration_hours", models.FloatField()),
                ("water_used_liters", models.IntegerField(blank=True, null=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "ticket",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outcome",
                        to="UdyanSaathiAPI.dispatchticket",
                    ),
                ),
            ],
            options={
                "db_table": "intervention_logs",
            },
        ),
    ]
