# Generated by Django 5.2.9 on 2025-12-28 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("UdyanSaathiAPI", "0005_fleetasset_dispatchticket_interventionlog"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ward",
            fields=[
                (
                    "ward_id",
                    models.IntegerField(primary_key=True, serialize=False, unique=True),
                ),
                ("ward_name", models.CharField(max_length=100)),
                ("city", models.CharField(default="Delhi", max_length=100)),
                ("state", models.CharField(default="Delhi", max_length=100)),
                (
                    "boundary_geojson",
                    models.JSONField(help_text="GeoJSON polygon of ward boundary"),
                ),
                ("center_lat", models.FloatField()),
                ("center_lon", models.FloatField()),
                ("area_sq_km", models.FloatField(blank=True, null=True)),
                ("population", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "wards",
                "ordering": ["ward_id"],
            },
        ),
        migrations.CreateModel(
            name="WardStationMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("station_name", models.CharField(max_length=200)),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                (
                    "is_primary_station",
                    models.BooleanField(
                        default=False, help_text="Main station for this ward"
                    ),
                ),
                ("distance_from_center_km", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "ward",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stations",
                        to="UdyanSaathiAPI.ward",
                    ),
                ),
            ],
            options={
                "db_table": "ward_station_mapping",
                "unique_together": {("ward", "station_name")},
            },
        ),
    ]
